scrape_configs:
  - job_name: "sample-monitoring"
    scrape_interval: 5s
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:8081', 'host.docker.internal:8082', 'host.docker.internal:8083',
                  'host.docker.internal:8084']