version: '3.8'

services:
  kafka:
    image: bitnami/kafka
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    networks:
      - app-network
    restart: always

  eureka-server:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      EUREKA_SERVER_URL: http://eureka-server:8761/eureka/
    healthcheck:
      test: [ "CMD-SHELL", "curl --write-out '%{http_code}' --silent --output /dev/null http://localhost:8761/eureka/" ]
      interval: 10s
      retries: 5
      start_period: 15s
      timeout: 10s
    networks:
      - app-network

  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: cab-aggregator-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 98479847
    ports:
      - "8180:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 10s
      retries: 5
      start_period: 15s
      timeout: 10s
    networks:
      - app-network

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    networks:
      app-network:
        aliases:
          - prometheus
    volumes:
      - ./scripts/config/prometheus.yml:/etc/prometheus/prometheus.yml
    restart: always

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    networks:
      app-network:
        aliases:
          - grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    restart: always

  passenger-microservice:
    build:
      context: /Users/aliaksei/Desktop/Modsen/passenger-microservice
      dockerfile: Dockerfile
    restart: always
    container_name: passenger-microservice
    depends_on:
      eureka-server:
        condition: service_healthy
      postgres:
        condition: service_healthy
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/cab-aggregator-db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 98479847
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      EUREKA_SERVER_URL: http://eureka-server:8761/eureka/
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    healthcheck:
      test: [ "CMD-SHELL", "curl --write-out '%{http_code}' --silent --output /dev/null http://localhost:8081" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    networks:
      - app-network

  driver-microservice:
    build:
      context: /Users/aliaksei/Desktop/Modsen/driver-microservice
      dockerfile: Dockerfile
    restart: always
    container_name: driver-microservice
    depends_on:
      eureka-server:
        condition: service_healthy
      postgres:
        condition: service_healthy
      passenger-microservice:
        condition: service_healthy
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/cab-aggregator-db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 98479847
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      EUREKA_SERVER_URL: http://eureka-server:8761/eureka/
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    healthcheck:
      test: [ "CMD-SHELL", "curl --write-out '%{http_code}' --silent --output /dev/null http://localhost:8082/" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    networks:
      - app-network

  rides-microservice:
    build:
      context: /Users/aliaksei/Desktop/Modsen/rides-microservice
      dockerfile: Dockerfile
    restart: always
    container_name: rides-microservice
    depends_on:
      driver-microservice:
        condition: service_healthy
    ports:
      - "8083:8083"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/cab-aggregator-db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 98479847
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      EUREKA_SERVER_URL: http://eureka-server:8761/eureka/
      PASSENGER_SERVER_URL: http://passenger-microservice:8081/api/passengers
      DRIVER_SERVER_URL: http://driver-microservice:8082/api/drivers
    healthcheck:
      test: [ "CMD-SHELL", "curl --write-out '%{http_code}' --silent --output /dev/null http://localhost:8083/" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    networks:
      - app-network

  rating-microservice:
    build:
      context: /Users/aliaksei/Desktop/Modsen/rating-microservice
      dockerfile: Dockerfile
    restart: always
    container_name: rating-microservice
    depends_on:
      rides-microservice:
        condition: service_healthy
    ports:
      - "8084:8084"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/cab-aggregator-db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 98479847
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      EUREKA_SERVER_URL: http://eureka-server:8761/eureka/
      RIDE_SERVER_URL: http://rides-microservice:8083/api/rides
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    healthcheck:
      test: [ "CMD-SHELL", "curl --write-out '%{http_code}' --silent --output /dev/null http://localhost:8084/" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    networks:
      - app-network

  api-gateway:
    build:
      context: /Users/aliaksei/Desktop/Modsen/api-gateway
      dockerfile: Dockerfile
    restart: always
    container_name: api-gateway
    depends_on:
      rating-microservice:
        condition: service_healthy
    ports:
      - "8765:8765"
    environment:
      EUREKA_SERVER_URL: http://eureka-server:8761/eureka/
    networks:
      - app-network

networks:
  app-network:
    driver: bridge