apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-cm
data:
  prometheus.yml: |
    scrape_configs:
      - job_name: "sample-monitoring"
        scrape_interval: 5s
        metrics_path: /actuator/prometheus
        static_configs:
          - targets: ['aggregator-passenger-service:81', 'aggregator-driver-service:82', 'aggregator-rides-service:83', 'aggregator-rating-service:84']
