apiVersion: apps/v1
kind: Deployment
metadata:
  name: aggregator-grafana-deployment
  labels:
    app: aggregator-grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aggregator-grafana
  template:
    metadata:
      labels:
        app: aggregator-grafana
    spec:
      containers:
        - name: aggregator-grafana
          image: grafana/grafana
          ports:
            - containerPort: 3000
          env:
            - name: GF_SECURITY_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: grafana-sec
                  key: grafana-admin-user
            - name: GF_SECURITY_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: grafana-sec
                  key: grafana-admin-password
