apiVersion: apps/v1
kind: Deployment
metadata:
  name: aggregator-kafka-deployment
  labels:
    app: aggregator-kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aggregator-kafka
  template:
    metadata:
      labels:
        app: aggregator-kafka
    spec:
      containers:
        - name: aggregator-kafka
          image: bitnami/kafka
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9092
            - containerPort: 9093
          env:
            - name: KAFKA_CFG_NODE_ID
              value: "0"
            - name: KAFKA_CFG_PROCESS_ROLES
              value: controller,broker
            - name: KAFKA_CFG_LISTENERS
              value: PLAINTEXT://:9092,CONTROLLER://:9093
            - name: KAFKA_CFG_ADVERTISED_LISTENERS
              value: PLAINTEXT://aggregator-kafka-service:9092
            - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
              value: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
            - name: KAFKA_CFG_CONTROLLER_QUORUM_VOTERS
              value: 0@aggregator-kafka-service:9093
            - name: KAFKA_CFG_CONTROLLER_LISTENER_NAMES
              value: CONTROLLER