apiVersion: v1
kind: Service
metadata:
  name: aggregator-driver-service
spec:
  type: NodePort
  ports:
    - port: 82
      targetPort: 8082
      protocol: TCP
  selector:
    app: aggregator-driver