apiVersion: v1
kind: Service
metadata:
  name: aggregator-passenger-service
spec:
  type: NodePort
  ports:
    - port: 81
      targetPort: 8081
      protocol: TCP
  selector:
    app: aggregator-passenger